version: '3'
services:
  db:
    image: postgres:14.2
    volumes:
      - ~/tmp/databasebackup:/tmp
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: meritoadmin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: merito_development
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      #zmienic sciezke po lewej stronie do takiej jaka odpowiada lokalnie dla programisty
      - /home/lisek/project-merito/backend/:/home/hosting/workspace/backend
      - /home/lisek/project-merito/frontend/:/home/hosting/workspace/frontend
      - ~/.ssh:/home/hosting/.ssh
    stdin_open: true
    tty: true
    depends_on:
      - db
volumes:
  pgdata: